@api = http://localhost:3000/
GET http://localhost:3000/inventario/DEMOA

###

GET http://localhost:3000/ventas/AXN000183

###

GET http://localhost:3000/ventas/DAXSL1970

###

GET http://localhost:3000/cxc/DAXSL1970

###

GET http://localhost:3000/clientes/DAXSL1970